- name: "mount share"
  mount:
    state: "mounted"
    fstype: "cifs"
    name: /home/eugene/mount
    src: "//NIFI-MSK/LocalApp"
    opts: "credentials=/home/eugene/.smb_passwords,file_mode=0644,dir_mode=0777,gid=eugene,uid=eugene"
    
- name: Download and extract files
  unarchive:
    src: /home/eugene/build-{{semaphore_vars.task_details.incoming_version}}.tar.gz
    dest: /home/eugene/mount
    remote_src: True
    
- name: Unmount SMB share
  mount:
    path: /home/eugene/mount
    state: unmounted

- name: Print version
  debug:
    msg: "Version {{ semaphore_vars.task_details.incoming_version }} is installed."