- name: Download and extract files
  unarchive:
    src: /home/eugene/build-{{semaphore_vars.task_details.incoming_version}}.tar.gz
    dest: //NIFI-MSK/LocalApp
    remote_src: True


- name: Print version
  debug:
    msg: "Version {{ semaphore_vars.task_details.incoming_version }} is installed."