- name: copy file from UNC path
  win_copy:
    src: /home/eugene/build/build-{{semaphore_vars.task_details.incoming_version}}/build-v{{semaphore_vars.task_details.incoming_version}}.tar.gz
    dest: \\NIFI-MSK\LocalApp\
    remote_src: True
  become: True
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: broadview
    ansible_become_pass: 302gOld!


- name: Print version
  debug:
    msg: "Version {{ semaphore_vars.task_details.incoming_version }} is installed."