- name: Transfer file to FTP server
  shell:
    cmd: "scp /home/eugene/build/build-{{semaphore_vars.task_details.incoming_version}}/build-v{{semaphore_vars.task_details.incoming_version}}.tar.gz broadview@172.20.4.124:C:\LocalApp"
  register: result

- name: Print version
  debug:
    msg: "Version {{ semaphore_vars.task_details.incoming_version }} is installed."
    
    shell: scp /home/osboxes/test osboxes@192.168.0.6: