- name: Download and extract files
  unarchive:
    src: /home/eugene/build/build-{{ semaphore_vars.task_details.incoming_version }}/build-v{{ semaphore_vars.task_details.incoming_version }}.tar.gz
    dest: "{{ dest_path }}"
    remote_src: True


- name: Print version
  debug:
    msg: "Version {{ semaphore_vars.task_details.incoming_version }} is installed."