- name: Mount SMB share
  mount:
    path: /mnt/smbshare
    src: '\\\\NIFI-MSK\\LocalApp'
    fstype: cifs
    state: mounted

- name: Download and extract files
  unarchive:
    src: /home/eugene/build-{{semaphore_vars.task_details.incoming_version}}.tar.gz
    dest: /mnt/smbshare
    remote_src: True
    
- name: Unmount SMB share
  mount:
    path: /mnt/smbshare
    state: unmounted

- name: Print version
  debug:
    msg: "Version {{ semaphore_vars.task_details.incoming_version }} is installed."