- name: Download and extract files
  unarchive:
    src: /home/eugene/build-{{semaphore_vars.task_details.incoming_version}}.tar.gz
    dest: ftp://NIFI-MSK/LocalApp
    remote_src: True
    
- name: Unmount SMB share
  mount:
    path: /home/eugene/mount
    state: unmounted

- name: Print version
  debug:
    msg: "Version {{ semaphore_vars.task_details.incoming_version }} is installed."