- name: Check curlftpfs package
  apt: name=curlftpfs state=present
  become: true

- name: Construct connection string
  set_fact: ftp_conn="ftp@172.20.4.124/localapp"
  when: ftp_conn is not defined

- name: Mount FTP
  command: curlftpfs user="eugene" "{{ ftp_conn }}" "/home/eugene/mount"


- name: Download and extract files
  unarchive:
    src: /home/eugene/build-{{semaphore_vars.task_details.incoming_version}}.tar.gz
    dest: ftp://NIFI-MSK/LocalApp
    remote_src: True
    
- name: Unmount SMB share
  mount:
    path: /home/eugene/mount
    state: unmounted

- name: Print version
  debug:
    msg: "Version {{ semaphore_vars.task_details.incoming_version }} is installed."